name: repair_project
description: A new Flutter application.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 1.0.14  #latest version
  http: '>=0.11.3+12'
  flutter_spinkit: "^3.1.0"
  cupertino_icons: ^0.1.2
  lpinyin: ^1.0.6
  flutter_statusbar: ^0.0.1
  device_info : ^0.2.0
  url_launcher: ^5.0.1
  flutter_slidable: ^0.4.9
  permission_handler: ^3.0.0
  transparent_image: ^0.1.0
  camera: ^0.4.2
  flutter_swiper: ^1.0.6
  fluttertoast: ^2.1.4
  video_player: ^0.7.2
  image_picker: ^0.4.10
  path_provider: ^0.5.0+1
  common_utils: 1.0.9
  shared_preferences: ^0.4.2
  json_annotation: ^2.0.0
  event_bus: 1.0.1
  connectivity: ^0.3.2
  flutter_refresh : ^0.0.2
  flutter_redux: ^0.5.2  #全局状态管理机
  percent_indicator: ^1.0.13
  smooth_star_rating: ^1.0.1
  city_picker: ^0.1.3
  circular_check_box: ^0.0.2
  image_cropper: ^1.0.1
  fluwx: ^0.6.2
  rxdart: ^0.22.0
  sqflite:
  path:
  cached_network_image:
  jpush_flutter : 0.0.11
  flutter_cache_manager : ^0.3.2
  qr_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^2.0.0
  build_runner: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/
    - assets/images/
    - assets/data/china.json
    - assets/data/contacts.json
#   - images/avatar.png
#   - images/sea.png
#   - images/star.jpg
#   - images/cat.jpg
#   - images/horse.jpg
#   - images/road.jpg
#   - images/test.png
#   - images/f1.png
#   - images/homepagebtn.png
#   - images/wxpay.png
#   - images/onsale(left).png
#   - images/onsale(right).png
#   - images/person_placeholder.png

#   - assets/images/coupon_bg_bottom.png
#   - assets/images/coupon_bg_right.png
#   - assets/images/coupon_bg_left.png
#   - assets/images/angelbaby.jpeg
#   - assets/images/alucard.jpg
#   - assets/images/logo.png
#   - assets/images/default_img.png
#   - assets/images/person_placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
      - family: myIcon
        fonts:
           - asset: assets/fonts/iconfont.ttf
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito.ttf